name: zikzak_share_handler_platform_interface
description: A common platform interface for the zikzak_share_handler plugin.
repository: https://github.com/arrrrny/zikzak_share_handler/tree/main/zikzak_share_handler_platform_interface
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_lints:
