name: zikzak_share_handler_windows
description: An implementation for the Windows platform of the Flutter zikzak_share_handler plugin.
repository: https://github.com/arrrrny/zikzak_share_handler/tree/main/zikzak_share_handler_platform_windows
version: 0.0.2

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_share_handler_platform_interface: ^0.0.7

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: ShareHandlerWindowsPlatform
