name: zikzak_share_handler_ios
description: An implementation for the iOS platform of the Flutter zikzak_share_handler plugin.
repository: https://github.com/arrrrny/zikzak_share_handler/tree/main/zikzak_share_handler_ios
version: 1.0.1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_share_handler_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ShareHandlerIosPlatform
        podspec: ios/zikzak_share_handler_ios.podspec
