name: zikzak_share_handler_ios
description: An implementation for the iOS platform of the Flutter zikzak_share_handler plugin.
repository: https://github.com/arrrrny/zikzak_share_handler/tree/main/zikzak_share_handler_ios
version: 0.0.17

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  zikzak_share_handler_platform_interface: ^0.0.7
  # zikzak_share_handler_platform_interface:
  #   path: ../zikzak_share_handler_platform_interface

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ShareHandlerIosPlatform
        podspec: ios/ShareHandlerIos.podspec
