name: zikzak_share_handler_web
description: An implementation for the Web platform of the Flutter zikzak_share_handler plugin.
repository: https://github.com/arrrrny/zikzak_share_handler/tree/main/zikzak_share_handler_web
version: 1.0.0

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  zikzak_share_handler_platform_interface: ^1.0.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ShareHandlerWebPlatform
        fileName: zikzak_share_handler_web.dart
